### ISSUE TITLE
safe-0.3.18 does not build on GHC 7.8 and earlier

### ISSUE THREAD

**Issue by RyanGlScott** [ndmitchell/safe#28]
I encountered this error on a [recent GHC 7.8 Travis build](https://travis-ci.org/goldfirere/th-desugar/jobs/620615816#L496):

```
Building library for safe-0.3.18..
[1 of 5] Compiling Safe.Partial     ( Safe/Partial.hs, dist/build/Safe/Partial.o )
[2 of 5] Compiling Safe.Util        ( Safe/Util.hs, dist/build/Safe/Util.o )
[3 of 5] Compiling Safe.Exact       ( Safe/Exact.hs, dist/build/Safe/Exact.o )
[4 of 5] Compiling Safe.Foldable    ( Safe/Foldable.hs, dist/build/Safe/Foldable.o )

Safe/Foldable.hs:44:21:
    Not in scope: ‘F.null’
    Perhaps you meant ‘F.all’ (imported from Data.Foldable)

Safe/Foldable.hs:45:21:
    Not in scope: ‘F.null’
    Perhaps you meant ‘F.all’ (imported from Data.Foldable)

Safe/Foldable.hs:52:22:
    Not in scope: ‘F.null’
    Perhaps you meant ‘F.all’ (imported from Data.Foldable)

Safe/Foldable.hs:53:22:
    Not in scope: ‘F.null’
    Perhaps you meant ‘F.all’ (imported from Data.Foldable)

Safe/Foldable.hs:60:24:
    Not in scope: ‘F.null’
    Perhaps you meant ‘F.all’ (imported from Data.Foldable)

Safe/Foldable.hs:61:24:
    Not in scope: ‘F.null’
    Perhaps you meant ‘F.all’ (imported from Data.Foldable)

Safe/Foldable.hs:80:21:
    Ambiguous occurrence ‘maximum’
    It could refer to either ‘F.maximum’,
                             imported from ‘Data.Foldable’ at Safe/Foldable.hs:26:1-25
                          or ‘Prelude.maximum’,
                             imported from ‘Prelude’ at Safe/Foldable.hs:29:1-14
                             (and originally defined in ‘Data.List’)

Safe/Foldable.hs:85:21:
    Ambiguous occurrence ‘minimum’
    It could refer to either ‘F.minimum’,
                             imported from ‘Data.Foldable’ at Safe/Foldable.hs:26:1-25
                          or ‘Prelude.minimum’,
                             imported from ‘Prelude’ at Safe/Foldable.hs:29:1-14
                             (and originally defined in ‘Data.List’)
```

Judging from [this commit](https://github.com/ndmitchell/safe/commit/351d9e7498014cc907004ef3bead6bcc371081b8#diff-354f30a63fb0907d4ad57269548329e3), it looks like dropping support for GHC 7.8 and earlier was intentional. If so, could you revise the upper version bounds for `safe-0.3.18` on Hackage so that it requires `base >= 4.8`?

**Comment by ndmitchell** [comment]
Oops! Thanks, revised on Hackage and committed to this repo so the next release won't regress.
